ribbon:
  IsSecure: false
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: FATAL
     org:
        springframework:
           web: WARN
           cloud: WARN
spring:
  application:
    name: ${vcap.application.application_name:cities-ui}
security:
  basic:
    enabled: false
pivotal:
  citiesServiceName: cities
  
---
spring:
  profiles: default
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/