spring:
  profiles.active: default
  
---
spring:
  profiles: default
  cities_ws_url: ${http://sboot-cities-service-cities-service.192.168.64.2.nip.io/cities:http://localhost:8080/cities}
server:
  port: 8081
