---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli

inputs:
  - name: cities-ui
  - name: resource-version

run:
  path: "cities-ui/ci/scripts/addVersionInfo.sh"
