---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java

inputs:
  - name: cities-ui
  - name: resource-version

outputs:
  - name: build

run:
  path: "cities-ui/ci/scripts/package.sh"
  args: [resource-version/number]
