---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: source-code

outputs:
  - name: build

run:
  path: "source-code/ci/package.sh"
