---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
  - name: cities-ui

run:
  path: "cities-ui/ci/scripts/testAppOnPCF.sh"
  args: ["-t", "Aldermoor", "-a", "api.run.haas-35.pez.pivotal.io", "-u", "skazi", "-p", "letmein", "-o", "skazi", "-s", "cities"]
