---
resources:
- name: cities-ui
  type: git
  source:
    uri: {{git-uri}}
  check_every: 8s

- name: resource-version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    initial_version: 0.0.0
    uri: {{GIT-SSH-URI}}
    private_key: {{GIT_KEY}}
    git_user: {{GIT_USER}}

- name: deployToPCF
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USERNAME}}
    password: {{CF_PASSWORD}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true

jobs:
- name: testSrc
  build_logs_to_retain: 5
  plan:
  - get: cities-ui
    trigger: true
  - task: test
    file: cities-ui/ci/tasks/test.yml

- name: checkDependencies
  build_logs_to_retain: 5
  plan:
  - get: cities-ui
    trigger: true
  - task: check-service
    file: cities-ui/ci/tasks/check-service.yml
    params:
      APPNAME: {{APPNAME}}
      CITIES_SERVICE_ROUTE: {{CITIES_SERVICE_ROUTE}}


- name: prepPCFSpace
  build_logs_to_retain: 5
  plan:
  - get: cities-ui
    passed:
      - checkDependencies
    trigger: true
  - task: create-cups
    file: cities-ui/ci/tasks/createCUPS.yml
    params:
      api: {{CF_API}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}
      CITIES_SERVICE_NAME: {{CITIES_SERVICE_NAME}}
      CITIES_SERVICE_ROUTE: {{CITIES_SERVICE_ROUTE}}

- name: packageAndDeploy
  build_logs_to_retain: 5
  plan:
  - get: cities-ui
    passed:
      - testSrc
      - prepPCFSpace
    trigger: true
  - get: resource-version
    params:
      bump: patch
  - task: package
    file: cities-ui/ci/tasks/package.yml
    params:
      APPNAME: {{APPNAME}}
  - put: resource-version
    params: {file: resource-version/number}
  - task: amendManifest
    file: cities-ui/ci/tasks/amendManifest.yml
    params:
      APPNAME: {{APPNAME}}
      username: {{CF_USERNAME}}
  - put: deployToPCF
    params:
      manifest: output/manifest.yml
      path: build/cities-ui-1.0.jar
      current_app_name: {{APPNAME}}
  - task: addVersionInfo
    file: cities-ui/ci/tasks/addVersionInfo.yml
    params:
      api: {{CF_API}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}

- name: testAppOnPCF
  build_logs_to_retain: 5
  plan:
  - get: cities-ui
    passed:
      - packageAndDeploy
    trigger: true
  - task: test
    file: cities-ui/ci/tasks/testAppOnPCF.yml
    params:
      api: {{CF_API}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}
