---
resources:
- name: cities-ui
  type: git
  source:
    uri: https://github.com/skazi-pivotal/spring-boot-cities-ui
  check_every: 7s

- name: deploy-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USERNAME}}
    password: {{CF_PASSWORD}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true

jobs:
- name: test-cities-ui
  plan:
  - get: cities-ui
    trigger: true
  - task: test
    file: cities-ui/ci/tasks/task_test.yml

- name: create-ui-env
  plan:
  - get: cities-ui
    trigger: true
  - task: create-cups
    file: cities-ui/ci/tasks/createCUPS.yml
    params:
      api: {{CF_API}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}

- name: deploy-cities-ui
  plan:
  - get: cities-ui
    trigger: true
    passed: [test-cities-ui, create-ui-env]
  - task: package
    file: cities-ui/ci/tasks/task_package.yml
  - put: deploy-app
    params:
      manifest: cities-ui/manifest.yml
      path: build/cities-ui-0.0.1-SNAPSHOT.jar
      current_app_name: {{APPNAME}}

- name: test-cities-app
  plan:
  - get: cities-ui
    trigger: true
    passed: [deploy-cities-ui]
  - task: test
    file: cities-ui/ci/tasks/testAppOnPCF.yml
    params:
      api: {{CF_API}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}
