apiVersion: apps/v1
kind: Deployment
metadata:
 name: cities-ui
spec:
 replicas: 1
 selector: 
   matchLabels:
      app: cities-ui
 template:
   metadata:
     labels:
       app: cities-ui
       date: "DATE"
   spec:
     containers:
     - name: cities-ui
       image: eu.gcr.io/sufcloudnative/cities-ui:latest
       imagePullPolicy: Always
       resources:
         requests:
           cpu: 100m
           memory: 100Mi
       ports:
       - containerPort: 8080
         name: "http-port"
       readinessProbe:
         httpGet:
           path: /actuator
           port: http-port
         initialDelaySeconds: 20
         timeoutSeconds: 5
         periodSeconds: 5
       livenessProbe:
         httpGet:
           path: /cities
           port: http-port
         initialDelaySeconds: 30
         timeoutSeconds: 10
         periodSeconds: 30
         failureThreshold: 3
